name: sales-performance-and-revenue-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.2.0
  - pyarrow=15.0.0
  - numpy=1.26.4
  - matplotlib=3.8
  - seaborn=0.13.2
  - scikit-learn=1.4.0
  - jupyterlab
  - pip
  - pip:
    - notebook
